alias ll='ls -lh --time-style=long-iso'
alias la='ls -alh --time-style=long-iso'
alias art='php artisan'
alias serve='php artisan serve --host 0.0.0.0'
alias migrate='php artisan migrate'
alias rollback='php artisan migrate:rollback'
alias fresh='php artisan migrate:fresh'
alias tinker='php artisan tinker'
alias relogin='exec $SHELL -l'
